version: '3.8'

services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile.ansible
    volumes:
      - ./ansible:/ansible
      - ~/.ssh:/root/.ssh:ro
    working_dir: /ansible
    command: ansible-playbook --version
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
